[versions]
compileSdk = "35"
minSdk = "23"
targetSdk = "35"
versionCode = "1"
versionName = "0.0.1"

accompanist = "0.36.0"
agp = "8.10.1"
coil = "2.7.0"
composeBom = "2025.06.00"
coroutines = "1.9.0"
detekt = "1.21.0"
koin = "4.0.2"
kotlin = "2.1.0"
kotlinxDatetime = "0.6.1"
ktor = "3.0.1"
legacySupportV4 = "1.0.0"
media3Exoplayer = "1.5.1"
navigation = "2.8.9"
skie= "0.10.1"
sqldelight= "2.0.2"
store5 = "5.1.0-alpha02"

[libraries]
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
android-sql-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
androidx-coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
androidx-legacy-support = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Exoplayer" }
androidx-media3-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3Exoplayer" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3Exoplayer" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-material = { group = "androidx.compose.material3", name = "material3" }
compose-material-adaptinve = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }
compose-coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
koin-android-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-ios = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ios-sql-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-primitive = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqldelight" }
store5 = { module = "org.mobilenativefoundation.store:store5", version.ref = "store5" }

[bundles]
compose = [ "androidx-navigation", "compose-coil", "compose-material", "compose-material-adaptinve", "compose-ui-preview" ]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }